### ISSUE TITLE
Offsets of segments triggered by actions

### ISSUE THREAD

**Issue by mittagessen** [chreul/LAREX#100]
Some actions trigger random, often quite large, offsets in the y-axis of manually created fixed segments and segments resulting from the combine action. It seems to happen randomly and only affect the user interface; the PageXML data is is uncorrupted. 

Unfortunately, I haven't found a way to trigger this bug reliably. Once I've done so I'll upload some sample data.

**Comment by NesbiDevelopment** [comment]
Thank you. I will look into that. Did it resolve when reselecting the page? Or does it persist even after that?

**Comment by mittagessen** [comment]
Reselecting the page (or moving to another one) doesn't solve it, reloading the whole application in browser does. It also only seems to happen when the underlying page image has been panned.

**Comment by NesbiDevelopment** [comment]
Offset of fixed segments, that could result after a segmentation through up and down scaling of the image for the segmentation algorithm, has been corrected.

Closed, unless other problems occur.
