### ISSUE TITLE
Incompatible with Java 10+

### ISSUE THREAD

**Issue by NesbiDevelopment** [chreul/LAREX#123]
Larex does currently not support running on Java 10 and up, cause of a dependency that is incompatible with Java 10 and up. 

The OpenCV Maven artifact openpnp/opencv has already acknowledge the problem.
https://github.com/openpnp/opencv/issues/33#issue-328668054

We may folk openpnp's opencv repository to implement a temporary fix that then will be uploaded to  the maven artifactory of the University of Würzburg Chair of Artifical Intelligence.

**Comment by NesbiDevelopment** [comment]
The work on the forked openpnp/opencv version turned out to be unfeasible, with our current resources.
We're are currently waiting for updates in the issue of the openpnp/opencv with java 10, while looking for other alternatives.

**Comment by vonnieda** [comment]
Hi folks, https://github.com/openpnp/opencv/issues/33 is now fixed so you should be able to upgrade and be back in business.

**Comment by NesbiDevelopment** [comment]
Thank you very much.
We will shortly update to the newest version.
Thank you for your work!

**Comment by NesbiDevelopment** [comment]
Larex has now updated to openpnp/opencv 3.4.2-1 in order to support Java 10 and up.
