### ISSUE TITLE
Clicking the File->PageXML Button should download the xml-file only once

### ISSUE THREAD

**Issue by ChWick** [chreul/LAREX#21]
When using the PageXML Button of the file menu bar, the page is downloaded twice. This behavior is confirmed on chrome and firefox.
The Export as PageXML Button on the side panel works as expected

**Comment by NesbiDevelopment** [comment]
A debug function caused page 0 to be exported every time the PageXML Button in the file menu bar is pressed.
This debug functionality was removed. The button now behaves as expected.
