### ISSUE TITLE
Default region positions stop working after being resized or moved

### ISSUE THREAD

**Issue by chreul** [chreul/LAREX#22]
When a position of a default region (e. g. the page-number position at the top of the page) gets resized or moved it stops working ->comprised segments aren't classified correctly anymore.
User created positions can be resized or move without any problems.

**Comment by NesbiDevelopment** [comment]
Fixed with 3679374 + fa43cf8
The functionality to cut off polygons, when they overlap the picture, did cause this problem.
Overlapping polygons will not be cut off from now on.
Scaling objects is now restricted to the image.
