### ISSUE TITLE
book directory with special characters ignored

### ISSUE THREAD

**Issue by jze** [chreul/LAREX#33]
If a directory in the book folder contains a 'special character' such as an ö it is ignored in the list of books.

**Comment by NesbiDevelopment** [comment]
I where unable to reproduce this issue on Linux Fedora. (Tested with Chrome and Firefox)
What operating system and browser are you using? And what other special characters seem to cause the issue?

![special char](https://user-images.githubusercontent.com/23743591/27010492-31eb6d88-4ea6-11e7-9e00-8c342e573a12.png)

**Comment by NesbiDevelopment** [comment]
As a side note: 
Characters reserved to specific functionalities in URLs that would be allowed in naming folders, such as **?** and **&** can cause problems in loading the images. But I was unable to reproduce this issue even with those characters.

**Comment by jze** [comment]
This is probably a problem with my Docker container. I use a volume to connect the container with the outside world. Inside the Docker container a directory called "schön" will become "sch??n". 
So this is a minor and rather exotic problem. I am going to take a look at it in the Java code.
