### ISSUE TITLE
Segment select Issues

### ISSUE THREAD

**Issue by chreul** [chreul/LAREX#43]
- It should be possible to deselect a single segment while keeping the rest of the selected segments (Ctrl + left click).
- Selected segments should get deselected when the user clicks at a spot where no segments are located.
- It should be possible to add several segements to a selection by holding down Ctrl and selecting the additional segments by drawing a rectangle.

**Comment by NesbiDevelopment** [comment]
Added all requests in last commit ac8c9d2
