### ISSUE TITLE
Adding fixed segments without re-running the segmentation

### ISSUE THREAD

**Issue by chreul** [chreul/LAREX#51]
It should be possible to add fixed segments without re-running the segmentation.
When the result is saved/exported fixed segments which have been added after the last segmentation run should be treated as final segments. Obviously, this could lead to overlapping segments but to deal with this lies within the responsibility of the user.

**Comment by NesbiDevelopment** [comment]
Fixed Segments no longer create duplicated result regions.
Floating fixed segments will be added to the output.
