### ISSUE TITLE
Saving final result

### ISSUE THREAD

**Issue by chreul** [chreul/LAREX#53]
- When saving the final result via "Export PageXML" (should be renamed to "Save Result" or something similar) the corresponding page should be marked by a symbol (just like when downloading the PageXML).
- When returning to a page whose final result has been already saved, the final result should be displayed instead of the result that was produced by the automatic segmentation.
- A keyboard shortcut would be nice.

**Comment by NesbiDevelopment** [comment]
Has been added and merged into master
