### ISSUE TITLE
Combined segments do not show up in XML

### ISSUE THREAD

**Issue by andbue** [chreul/LAREX#65]
If segments are combined pressing "c", they don't show up in the xml export any more.

**Comment by andbue** [comment]
Sorry, I'm wrong, forgot to click "segment" after combining.

**Comment by chreul** [comment]
I will reopen this because the user shouldn't be forced to run the segmentation again in order to merge segments, especially as long as #66 isn't fixed.

**Comment by NesbiDevelopment** [comment]
Merged segments will now be displayed without rerunning "Segment". See #51 for more info. (Merged Segments were handled as fixed segments)
