### ISSUE TITLE
PageXML Version

### ISSUE THREAD

**Issue by chreul** [chreul/LAREX#69]
Supporting an older PageXML-Version with a different representation of the coordinates of a region contour would be nice. The user should be able to choose between the two outputs.

**Comment by NesbiDevelopment** [comment]
PageXML version has temporarily been changed to version 2010. 
Settings to select a desired PageXML version (at least 2010 and 2013) will be added.

**Comment by NesbiDevelopment** [comment]
Different PageXML versions can now be selected before downloading. (2013-07-15 and 2010-03-19)
dea7a32
