### ISSUE TITLE
Use Maven OpenCV

### ISSUE THREAD

**Issue by NesbiDevelopment** [chreul/LAREX#71]
Switch to Maven compatible OpenCV version to widen compatibility

**Comment by ChWick** [comment]
Use this: https://mvnrepository.com/artifact/org.openpnp/opencv

**Comment by NesbiDevelopment** [comment]
Has been added on testing branch 9132679
Seems promising and simplifies the installation process by a lot, but needs additional testing on different OSs.

**Comment by NesbiDevelopment** [comment]
Tested on multiple Systems and OSs. 
It seems stable enough and has been merged into master.
