### ISSUE TITLE
Load existing PageXML

### ISSUE THREAD

**Issue by chreul** [chreul/LAREX#73]
When a new page is loaded and the input folder contains the matching PageXML file the comprised segmentation should be loaded and displayed.
If the segmentation contains regions which haven't been defined yet the user should be warned and be able to add the required regions right away.

**Comment by NesbiDevelopment** [comment]
#82a1b59
Enable to load results from pageXMLs.
* Added button to upload pageXMLs
* Added button to load pageXMLs existing in the book folder
* Added lever to automatically load pageXMLs if they exist in the book folder

Issue #80 
The reading order is currently not processed
