### ISSUE TITLE
Question: Howto create a new "book"?

### ISSUE THREAD

**Issue by wrznr** [chreul/LAREX#74]
After successfully compiling and running LAREX, I try to figure out how to add a new book to the LAREX Library. What I have tried so far is to create a new directory under `LAREX/Larex/target/Larex/resources` (i.e next to `Test`) and put some JPEG file into it. But it does not show up in the web app even after restarting the tomcat server. It would be great if @chreul could give me some hint. Thanks in advance.

**Comment by NesbiDevelopment** [comment]
Greetings wrznr.
For an image to appear in the webapp, you have to put it into a folder inside of the ../resources/books directory.
You could for example go into the directory `LAREX/Larex/target/Larex/resources/books`create a folder named `Test` and add your images into that folder. Visiting the main page [http://localhost:8080/Larex/](http://localhost:8080/Larex/) should automatically update the library and display a book called `Test`. Clicking on it will open the viewer with your images.

I hope this helps.

**Comment by wrznr** [comment]
@NesbiDevelopment Many thanks for the information. But that is exactly the approach I took (and described in the initial post). Are there restrictions on the image formats? I only used JPEG images so far.

**Comment by NesbiDevelopment** [comment]
No worries, I'm happy to help.
Yes there is a restriction on image formats, currently supported are jpg, jpeg and png.

The subfolder 'books' is important and the shipped example document called Test is in that folder. 
But Github displays it as 'books/Test' which could have lead to confusions. 
(Github likes to combine simple directories)

**Comment by wrznr** [comment]
Alright. I got it. Again, many thanks for your (immediate) support.

**Comment by wrznr** [comment]
@NesbiDevelopment, sorry to get back to you: The procedure you described above does not work.

```
kmw@barclay:~/built/LAREX/Larex/target/Larex/resources/books$ ls -l
total 8
drwxrwxr-x 2 kmw kmw 4096 Okt  5 14:37 BAZ
drwxrwxr-x 2 kmw kmw 4096 Okt  5 14:28 Test
```
That's the layout of my `books` directory. However, even after restarting the tomcat server, the book `BAZ` does not show up. I also tried to copy an additional image file to `Test` without success. Any hints are very much appreciated.

**Comment by wrznr** [comment]
@NesbiDevelopment Figured it out: The correct `books` directory lives (in my particular case) in `/var/lib/tomcat8/webapps/Larex/resources/`.

**Comment by alexander-winkler** [comment]
A follow-up on this issue: I had to copy my own book in the `tomcat8` subfolder as well in order for it to show up. However, when I open the book in Larex I get an "Error code: 500" message. My `/var/lib/tomcat8/webapps/Larex/resources/books`-folder is structured as follows:

```
MY_OWN_BOOK/
├── 0021.bin.png
├── 0021.nrm.png
├── 0021.xml
├── 0022.bin.png
├── 0022.nrm.png 
```

Thanks for any help!
