### ISSUE TITLE
Loading XML/Result generates faulty XML after setting/generating Reading Order

### ISSUE THREAD

**Issue by maxnth** [chreul/LAREX#86]
When loading a previously exported XML and then setting or generating a reading order the newly exported XML file will only contain the following text.
`<?xml version="1.0" encoding="UTF-8" standalone="no"?>`

**Comment by NesbiDevelopment** [comment]
I was able to recreate it and it should be fixed now.
Thank you for bringing it to our attention and sorry for the inconvenience.
