### ISSUE TITLE
"Load existing segmentations" generates false file names

### ISSUE THREAD

**Issue by maxnth** [chreul/LAREX#88]
When *Settings* → *Advanced Settings* → *Load existing segmentations* is activated Larex gives all newly generated XML files the same file name as the page where "Load existing segmentation" was activated for the first time.

For example: 
When you activate *Load existing segmentations* for the first time on page 0020 all files in the current session will be saved as 0020.xml. 

This can only be stopped by clearing the cache or restarting tomcat, even when *Load existing segmentations* is unchecked.
This behaviour is not triggered when only using *Load Now*.

**Comment by NesbiDevelopment** [comment]
Hello, sorry for the inconvenience the bug should be fixed with the newest hotfix 7ce139c
