### ISSUE TITLE
Larex stops working after processing several pages when using "LOAD NOW"

### ISSUE THREAD

**Issue by maxnth** [chreul/LAREX#89]
When using *LOAD NOW* Larex stops working after processing 2-3 pages (tested with Chrome and Firefox). 
Larex then only shows the "loading circle" and you can't switch to other pages. You can still work on the currently selected page though.

Console Error Message:

> Segmentation load: failed error
> controller.js:253 Uncaught TypeError: Cannot read property 'result' of undefined
>     at http://localhost:8080/Larex/resources/js/viewer/controller.js:253:22
>     at Array.forEach (<anonymous>)
>     at Object.<anonymous> (http://localhost:8080/Larex/resources/js/viewer/controller.js:252:11)
>     at j (https://code.jquery.com/jquery-2.1.1.min.js:2:26860)
>     at Object.fireWith [as resolveWith] (https://code.jquery.com/jquery-2.1.1.min.js:2:27673)
>     at Object.e.(anonymous function) [as resolve] (https://code.jquery.com/jquery-2.1.1.min.js:2:28653)
>     at Object.error (http://localhost:8080/Larex/resources/js/viewer/communicator.js:67:12)
>     at j (https://code.jquery.com/jquery-2.1.1.min.js:2:26860)
>     at Object.fireWith [as rejectWith] (https://code.jquery.com/jquery-2.1.1.min.js:2:27673)
>     at x (https://code.jquery.com/jquery-2.1.1.min.js:4:11145)

**Comment by NesbiDevelopment** [comment]
I'm unable to reproduce the issue. Do you still experience the bug after the newest Hotfix 7ce139c ?
(Could be the same Issue as #89 )

**Comment by maxnth** [comment]
Bug is gone after the Hotfix. Thank youn very much.
