### ISSUE TITLE
PageXML Version

### ISSUE THREAD

**Issue by andbue** [chreul/LAREX#90]
Is there a reason for the newest PageXML version being 2013 (#69)? It would be great to have the bleeding edge technology of version 2017-07-15 available as an option. ;-)

**Comment by NesbiDevelopment** [comment]
Hello, the versions 2013 and 2017 seem nearly identical for our purpose.
With version 2017 present, we do not see a purpose of version 2013. 
Version 2013 has therefore been replaced with version 2017 (594c97f)
