### ISSUE TITLE
Newest version doesn't allow to open any image/page in Chrome

### ISSUE THREAD

**Issue by maxnth** [chreul/LAREX#92]
The newest available version doesn't allow to load any page in Chrome. 
The thumbnails will get loaded but only the throbber in the page view is displayed.
Right after opening the book the following error message is displayed in the console.

> Book load: start                            communicator.js:29 
> Book load: successful                   communicator.js:32 
> Uncaught TypeError: Cannot read property 'complete' of undefined                  controller.js:119 
>     at Controller.displayPage (http://localhost:8080/Larex/resources/js/viewer/controller.js:119:18)
>     at Object.<anonymous> (http://localhost:8080/Larex/resources/js/viewer/controller.js:98:24)
>     at j (https://code.jquery.com/jquery-2.1.1.min.js:2:26860)
>     at Object.fireWith [as resolveWith] (https://code.jquery.com/jquery-2.1.1.min.js:2:27673)
>     at Object.e.(anonymous function) [as resolve] (https://code.jquery.com/jquery-2.1.1.min.js:2:28653)
>     at Object.success (http://localhost:8080/Larex/resources/js/viewer/communicator.js:33:12)
>     at j (https://code.jquery.com/jquery-2.1.1.min.js:2:26860)
>     at Object.fireWith [as resolveWith] (https://code.jquery.com/jquery-2.1.1.min.js:2:27673)
>     at x (https://code.jquery.com/jquery-2.1.1.min.js:4:11120)
>     at XMLHttpRequest.<anonymous> (https://code.jquery.com/jquery-2.1.1.min.js:4:14767)

**Comment by NesbiDevelopment** [comment]
The last update change a lot in the Javascript code. 
It seems like your browser is still running the old *.js files with the new Server which normally won't do much harm, but in this case made the app unusable.

Could you please try to empty the browser cache? CTRL+Shift+R in most browsers.
This should normally resolve the issue.

**Comment by maxnth** [comment]
Clearing the browser cache sadly didn't resolve the issue for me (neither in Chrome nor in Firefox relating to #93)
I'll try it on a different PC later on to check if it only appears on my current set up.
