### ISSUE TITLE
"Load existing segmentations" generates false file names again

### ISSUE THREAD

**Issue by maxnth** [chreul/LAREX#93]
The formerly resolved bug from issue #88 is back again in the newest version.
Only tested in Firefox because of bug #92.

**Comment by NesbiDevelopment** [comment]
I'm sorry but I'm unable to reproduce the issue.

Could you please try to empty the browser cache (CTRL+Shift+R in most browsers) and report back if something changed?

**Comment by NesbiDevelopment** [comment]
I was now able to reproduce the issue. Don't know why I wasn't 6 days ago.

Never the less it should now be fixed with 6cd15d7
