### ISSUE TITLE
Larex always loads segmentation for first page

### ISSUE THREAD

**Issue by andbue** [chreul/LAREX#94]
If there is an existing PageXML containing segmentation in the books folder, LAREX always loads the segmentation for the first page, even if "Load existing segmentation" is not activated. Segmentation for other pages is ignored until the user changes the settings.

**Comment by NesbiDevelopment** [comment]
Hello, andbue, thank you for the notice.
The issue has now been fixed with 45c94f6 and the behavior was just a little oversight on my part after testing the feature.
