### ISSUE TITLE
Combining fixed and automatic areas 

### ISSUE THREAD

**Issue by mittagessen** [chreul/LAREX#97]
The connected component approach doesn't work terribly well for my data causing a fairly large number of non-recognized text parts no matter the parametrization of the segmenter (might be worse than usual because I need text lines and not paragraphs so fiddling with the y-dilation doesn't really help here).

It would be quite helpful to be able to combine manually created fixed areas with automatically generated ones, upgrading the combined area to a fixed one.

**Comment by NesbiDevelopment** [comment]
I'll mark this as an important enhancement. We would like this feature, but are currently working on another complex one that could help with your problem. (More about the feature when it is usable)

But I'll see about combining fixed segments with generated ones in the future.

**Comment by NesbiDevelopment** [comment]
The feature has been added in the last huge merge.

Fixed and result segments are no longer separated. Features like combining them are therefore possible now.
