### ISSUE TITLE
Preserve region classes when resegmenting

### ISSUE THREAD

**Issue by mittagessen** [chreul/LAREX#98]
Resegmenting, e.g. because of new cut lines, will erase manually assigned classes. Those should be preserved, otherwhise there is no way to fix a faulty segmentation but by erasing the pertinent regions and drawing bounding boxes manually.

**Comment by NesbiDevelopment** [comment]
Preserving those actions after a re-segmenting is quite difficult. And would require heavy rewrites. The segmentation can change completely when changes in regions and segmentation settings are performed. 

But what exactly do you mean by faulty segmentation? Maybe we can think of a different solution.

**Comment by mittagessen** [comment]
Sorry for being unclear. Let's say you start with the segmenter output, assigning classes to parts of the page. Halfway through you see that some element is missegmented, e.g. marginalia and text body regions are merged. Naturally, I'd use the cut tool to separate those areas and resegment but now all previous manual annotation is lost. 

Mind you, I haven't read the source code so I don't know the internal data model but naively I'd expect segments with a manually assigned class to be treated the same as a manually created fixed segment. Currently, I'd have to do two runs over a page, first fixing any segmentation errors (through cut/combine and potentially fixed segments), running the segmenter again, and finally assigning classes while a annotation preserving resegment would allow me to do annotation and potential segmentation fixes in a single pass.

**Comment by NesbiDevelopment** [comment]
The merged branch ClientServer#102 should now make this possible.

Changed segments will now automatically been fixed and be preserved throughout a segmentation.
